<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LastName</name>
   <tag></tag>
   <elementGuidId>c2d3e4f5-a6b7-4c2d-9e45-162384516273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rampsite_registration_last_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#rampsite_registration_last_name</value>
      <webElementGuid>c2d3e4f5-a6b7-4c2d-9e45-162384516274</webElementGuid>
   </webElementProperties>
</WebElementEntity>
