<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FirstName</name>
   <tag></tag>
   <elementGuidId>b1c2d3e4-f5a6-4b1c-8d34-095162384516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rampsite_registration_first_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#rampsite_registration_first_name</value>
      <webElementGuid>b1c2d3e4-f5a6-4b1c-8d34-095162384517</webElementGuid>
   </webElementProperties>
</WebElementEntity>
