<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Country</name>
   <tag></tag>
   <elementGuidId>a4b5c6d7-e8f9-4a4b-9c5d-6e7f80910215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rampsite_registration_country_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#rampsite_registration_country_id</value>
      <webElementGuid>a4b5c6d7-e8f9-4a4b-9c5d-6e7f80910216</webElementGuid>
   </webElementProperties>
</WebElementEntity>
