<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OrgCountry</name>
   <tag></tag>
   <elementGuidId>c6d7e8f9-a0b1-4c6d-9e7f-809102152839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rampsite_registration_organization_country_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#rampsite_registration_organization_country_id</value>
      <webElementGuid>c6d7e8f9-a0b1-4c6d-9e7f-809102152840</webElementGuid>
   </webElementProperties>
</WebElementEntity>
