<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit Your Email and Resend</name>
   <tag></tag>
   <elementGuidId>920cdfd9-f12f-4587-a903-b85c64408517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'confirmation-edit-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;confirmation-edit-email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;confirmation-edit-email&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edbf51ed-aba7-40a9-b427-b15e90b99ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-outlined MuiButton-sizeMedium MuiButton-colorPrimary css-fclcll</value>
      <webElementGuid>3af69b57-211b-4dd9-8f6b-f88c618026c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>69e7bccb-fcb2-468a-b1ba-05f35f79256a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77cb9421-b099-4c12-a820-ebc5820c3133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>confirmation-edit-email</value>
      <webElementGuid>78a3aa9e-4a9c-4b4a-a1c5-9a250caaa356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Your Email and Resend</value>
      <webElementGuid>417dbc1d-0f32-407a-b771-cfa7ce127e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-324e6bb9afe5e4dc438f32fab91f1831</value>
      <webElementGuid>2c8cc7f2-2bab-4fbe-a730-b2fb63fe751c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'confirmation-edit-email']</value>
      <webElementGuid>72a02058-8339-4f5c-9b33-30c63faa9852</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'confirmation-edit-email']</value>
      <webElementGuid>5cb45c49-2fc4-496f-a98e-fedb35f84ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Edit Your Email and Resend' or . = 'Edit Your Email and Resend')]</value>
      <webElementGuid>e262ce56-e159-4580-9382-cf3e7e74e21d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
