<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update and Resend</name>
   <tag></tag>
   <elementGuidId>1283fbf5-006d-4d20-80fc-72f063f895e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'confirmation-update-resend']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;confirmation-update-resend&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;confirmation-update-resend&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>318b3255-64fc-4584-8643-38de2695aff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-sizeMedium MuiButton-colorPrimary css-1wde728</value>
      <webElementGuid>cfc39e25-e89c-47f3-a8a0-6083fff2b71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>460f7b6c-f5e0-4ed1-8d0b-c009e10508b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1612ca16-5ed3-46a8-a443-acb50a66fcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>confirmation-update-resend</value>
      <webElementGuid>fd09532b-9b3d-4483-baf3-e6f508ad6ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update and Resend</value>
      <webElementGuid>97044a90-cdd5-4911-91fe-04c81dc03b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-76f0219872c7e1f60eaf42c6bf13dfe7</value>
      <webElementGuid>344c1d8e-2d2d-435e-bc33-dab8976bbb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'confirmation-update-resend']</value>
      <webElementGuid>9bd85c56-bdfb-4838-8e07-c90f292c1e47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'confirmation-update-resend']</value>
      <webElementGuid>1313fc8f-5b12-49ef-a8fe-0d9268d65d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Update and Resend' or . = 'Update and Resend')]</value>
      <webElementGuid>dd92a9fe-d9de-4800-9742-a21fed275e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
