<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_SCiEnableSCiSupplier</name>
   <tag></tag>
   <elementGuidId>df21a7f6-f724-440c-ab44-ff25e6fa112c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.AppSwitcher-list.MuiBox-root.css-14abxdd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SCiEnableSCiSupplier&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>6cabb9a8-5c13-4411-a222-ba3afa8e5236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AppSwitcher-list MuiBox-root css-14abxdd</value>
      <webElementGuid>d527cac0-31f8-4d36-be41-05510e0197ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SCiEnableSCiSupplier</value>
      <webElementGuid>642d1dcf-e323-4e7c-9ea4-f6805d42c473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-12x4niu&quot;]/nav[@class=&quot;MuiBox-root css-66ye6z&quot;]/ul[@class=&quot;AppSwitcher-list MuiBox-root css-14abxdd&quot;]</value>
      <webElementGuid>aee66078-d684-494b-b806-8ff271d089fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/ul</value>
      <webElementGuid>934e1a89-2e0b-450f-b6ce-9ca98d7db336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>8d3aef9e-5bda-4314-a301-0f129d084591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'SCiEnableSCiSupplier' or . = 'SCiEnableSCiSupplier')]</value>
      <webElementGuid>def8e6be-6978-41f7-b801-2b0d06f8f96b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
