<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_search_supplier_icon</name>
   <tag></tag>
   <elementGuidId>c4579ea2-375d-4e3c-a138-440b7a452dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'search_supplier_icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search_supplier_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#search_supplier_icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a4b0ff71-d0bd-44ad-ab81-9d1b3a905701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_supplier_icon</value>
      <webElementGuid>064718c1-fcae-4f0b-a668-74b0a6e95f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>search_supplier('')</value>
      <webElementGuid>035a01ab-c0cb-4245-a9fb-113acc5b7671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_program_supplier_icon</value>
      <webElementGuid>fc0f09d1-9bc9-4ca8-a807-f7f3afc0c3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/search-cc05fe9c7c93eab378f15ca73c2e2c067be5a3e29d9372e712b44a97a75fbbce.png</value>
      <webElementGuid>8b587ff5-47b5-4c38-89bd-43a0016a08b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7ec7001f04648748650b400d9c323a0d</value>
      <webElementGuid>437b7cc0-53c6-4f2e-bd2a-72716daec68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'search_supplier_icon']</value>
      <webElementGuid>fa7b6832-a52d-45cd-be02-d3e7e641dff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'search_supplier_icon']</value>
      <webElementGuid>cd2851a0-7765-43d9-bc0b-16dd685998f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'search_supplier_icon' and @src = '/assets/search-cc05fe9c7c93eab378f15ca73c2e2c067be5a3e29d9372e712b44a97a75fbbce.png']</value>
      <webElementGuid>33ef5004-486f-48b7-b6de-923f71a51697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
