<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ui-id-37</name>
   <tag></tag>
   <elementGuidId>62db3c1b-c3a8-4eb1-8d47-7bfddeacb533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ui-menu-item ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.ui-menu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui-id-37</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>919df814-b970-428b-9564-1073e0ecaa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>66411e9d-1e67-4fff-bfb3-f8dddb2bee3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-37</value>
      <webElementGuid>c540585e-9eef-43ff-bedb-76600cb6fa66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3e7835bf-af13-4f2c-8241-ea2beae7a0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Smoke Supplier 1006130954</value>
      <webElementGuid>7cfc961e-b12c-41dd-9def-6326307995d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a6b8f4b02d94abbf3b17fa5b2b62acca</value>
      <webElementGuid>c17bd7a9-5944-4412-9e45-19e85898b778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ui-menu-item ')]</value>
      <webElementGuid>b39cd8d5-45e6-4f0f-b9a7-7b9c9707ad84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ui-menu-item ')]</value>
      <webElementGuid>339d8f5a-37ae-4150-8d63-941816cf280e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-37' and (text() = 'Smoke Supplier 1006130954' or . = 'Smoke Supplier 1006130954')]</value>
      <webElementGuid>a6f9af33-2b53-48b3-acd2-4f2f9f2963f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
