analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3439843,"name"\:"Sample - HR Web App \#3439843","teamId"\:3412549,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3475779,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3412549,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testreport.autoupload.manualstop.enable=false
