<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>App-switch control in the React shell header that navigates to the SCiEnable (onboarding) iframe. Verified live 9/23/2026 via Katalon Studio's Object Spy against a real logged-in session (supplier.scienable+iry123@gmail.com, regression.primerevenue.com) — it's an &lt;a&gt; tag, not a button as originally guessed.</description>
   <name>button_SwitchToSCiEnable</name>
   <tag></tag>
   <elementGuidId>a6b7c8d9-e0f1-4a6b-9c7d-8e9f0a1b2c3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'SCiEnable')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7c8d9e0-f1a2-4b7c-8d9e-9f0a1b2c3d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SCiEnable</value>
      <webElementGuid>c8d9e0f1-a2b3-4c8d-9e0f-0a1b2c3d4e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SCiEnable')]</value>
      <webElementGuid>d9e0f1a2-b3c4-4d9e-8f0a-1b2c3d4e5f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/ul/li/a</value>
      <webElementGuid>e0f1a2b3-c4d5-4e0f-9a1b-2c3d4e5f6a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
