<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>FusionAuth hosted login page password field. Verified live 9/21/2026 against access-dev.primerevenue.com.</description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>c6d7e8f9-a0b1-4c6d-9e7f-8a9b0c1d2e3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d7e8f9a0-b1c2-4d7e-8f9a-9b0c1d2e3f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e8f9a0b1-c2d3-4e8f-9a0b-0c1d2e3f4a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f9a0b1c2-d3e4-4f9a-8b0c-1d2e3f4a5b6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'password']</value>
      <webElementGuid>a0b1c2d3-e4f5-4a0b-9c1d-2e3f4a5b6c7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
